### ISSUE TITLE
E-Auto plötzlich nicht mehr separat ausgewiesen, sondern Teil von Hausverbrauch

### ISSUE THREAD

**Issue by koreolis845** [solectrus/senec-collector#594]
### Beschreibung

Vom einen auf den anderen Tag werden unsere SENEC Wallbox-Daten nicht mehr als "E-Auto", sondern als Hausverbrauch angezeigt.

IST-Stand SENEC App:

![Image](https://github.com/user-attachments/assets/e05f9d4c-2b9d-4d1c-819f-6e919f4e8335)

IST-Stand Solectrus: 

<img width="626" alt="Image" src="https://github.com/user-attachments/assets/d0487c8e-ece8-41d5-948f-15ecaedb83a1" />

Tag zuvor Solectrus:

<img width="713" alt="Image" src="https://github.com/user-attachments/assets/0f1a2740-2469-488f-85b8-939f811c4e26" />

### Welche Version von SOLECTRUS verwendest du?

0.19.1

### Auf welchem Gerät läuft bei dir SOLECTRUS?

Ubuntu

### Auszug aus dem Logfile, sofern zum Verständnis sinnvoll (z.B. bei einem Fehler 500)

```text

```

### Deine vollständige `docker-compose.yml` oder `compose.yml`

```yaml
services:
  dashboard:
    image: ghcr.io/solectrus/solectrus:latest
    depends_on:
      postgresql:
        condition: service_healthy
      influxdb:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - 3000:3000
    environment:
      - TZ
      - APP_HOST
      - FORCE_SSL
      - SECRET_KEY_BASE
      - WEB_CONCURRENCY
      - INSTALLATION_DATE
      - ADMIN_PASSWORD
      - FRAME_ANCESTORS
      - UI_THEME
      - CO2_EMISSION_FACTOR
      - DB_HOST=postgresql
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_USER=postgres
      - REDIS_URL
      - INFLUX_HOST
      - INFLUX_TOKEN=${INFLUX_TOKEN_READ}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_POLL_INTERVAL
      - INFLUX_SENSOR_INVERTER_POWER
      - INFLUX_SENSOR_HOUSE_POWER
      - INFLUX_SENSOR_GRID_IMPORT_POWER
      - INFLUX_SENSOR_GRID_EXPORT_POWER
      - INFLUX_SENSOR_BATTERY_CHARGING_POWER
      - INFLUX_SENSOR_BATTERY_DISCHARGING_POWER
      - INFLUX_SENSOR_BATTERY_SOC
      - INFLUX_SENSOR_WALLBOX_POWER
      - INFLUX_SENSOR_WALLBOX_CAR_CONNECTED
      - INFLUX_SENSOR_CASE_TEMP
      - INFLUX_SENSOR_INVERTER_POWER_FORECAST
      - INFLUX_SENSOR_SYSTEM_STATUS
      - INFLUX_SENSOR_SYSTEM_STATUS_OK
      - INFLUX_SENSOR_GRID_EXPORT_LIMIT
      - INFLUX_SENSOR_HEATPUMP_POWER
      - INFLUX_SENSOR_CAR_BATTERY_SOC
      - INFLUX_EXCLUDE_FROM_HOUSE_POWER
    healthcheck:
      test:
        - CMD-SHELL
        - nc -z 127.0.0.1 3000 || exit 1
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  influxdb:
    image: influxdb:2.7-alpine
    volumes:
      - ${INFLUX_VOLUME_PATH}:/var/lib/influxdb2
    environment:
      - TZ
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_ADMIN_TOKEN}
    command: influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store disk
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - influx
        - ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  postgresql:
    image: postgres:17-alpine
    environment:
      - TZ
      - POSTGRES_PASSWORD
    volumes:
      - ${DB_VOLUME_PATH}:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  redis:
    image: redis:7-alpine
    environment:
      - TZ
    volumes:
      - ${REDIS_VOLUME_PATH}:/data
    restart: unless-stopped
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 60s
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  senec-collector:
    image: ghcr.io/solectrus/senec-collector:latest
    environment:
      - TZ
      - SENEC_ADAPTER
      - SENEC_HOST
      - SENEC_SCHEMA
      - SENEC_INTERVAL
      - SENEC_LANGUAGE
      - SENEC_USERNAME
      - SENEC_PASSWORD
      - SENEC_IGNORE
      - SENEC_SYSTEM_ID
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_TOKEN_WRITE}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_MEASUREMENT=${INFLUX_MEASUREMENT_SENEC}
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  power-splitter:
    image: ghcr.io/solectrus/power-splitter:latest
    environment:
      - TZ
      - INFLUX_HOST
      - INFLUX_SCHEMA
      - INFLUX_PORT
      - INFLUX_TOKEN=${INFLUX_ADMIN_TOKEN}
      - INFLUX_ORG
      - INFLUX_BUCKET
      - INFLUX_SENSOR_HOUSE_POWER
      - INFLUX_SENSOR_GRID_IMPORT_POWER
      - INFLUX_SENSOR_WALLBOX_POWER
      - INFLUX_SENSOR_HEATPUMP_POWER
      - INFLUX_SENSOR_BATTERY_CHARGING_POWER
      - INFLUX_EXCLUDE_FROM_HOUSE_POWER
      - REDIS_URL
      - POWER_SPLITTER_INTERVAL
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    restart: unless-stopped
    depends_on:
      influxdb:
        condition: service_healthy
    links:
      - influxdb
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
  watchtower:
    image: containrrr/watchtower
    environment:
      - TZ
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --scope solectrus --cleanup
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: '3'
    labels:
      - com.centurylinklabs.watchtower.scope=solectrus
```

### Deine vollständige `.env`

```text
##################################################################
###                          Generic                           ###
##################################################################

TZ=Europe/Berlin

##################################################################
###                   Dashboard application                    ###
##################################################################

# Domain name or IP address of your host
APP_HOST=10.20.30.247

# Date of commissioning of your photovoltaic system
INSTALLATION_DATE=2022-03-01

# Password to login as administrator, required to manage settings like historical prices
ADMIN_PASSWORD=""

# Interval in seconds for polling the InfluxDB
INFLUX_POLL_INTERVAL=60

# SSL redirect: Use "true" if you want to auto-redirect to https, but ensure that you have a valid SSL certificate
# and a reverse proxy in front of the app!
# In all other cases, the option must be "false"!
FORCE_SSL=false

# Secret token to secure cookies, 128 chars long hexadecimal encoded string
SECRET_KEY_BASE=

# Start web server Puma in single mode (recommended to reduce memory usage)
WEB_CONCURRENCY=0

# Optional: Allow iframe embedding
# FRAME_ANCESTORS=https://my-other-home-automation-software.com

# Optional: Set factor to calculate CO2 emissions (default: 401 g/kWh)
# CO2_EMISSION_FACTOR=500

# Password for the PostgreSQL database, used by the app to communicate internally with the database
# Caution: Do not change this after the first run, otherwise the app will no longer be able to connect to the database!
POSTGRES_PASSWORD=my-secret-db-password

##################################################################
###                      Sensor mapping                        ###
##################################################################

# Where to find the data in the InfluxDB
# Each sensor must be mapped to a measurement and a field
# The format is: INFLUX_SENSOR_NAME=MEASUREMENT:FIELD
# Example: INFLUX_SENSOR_INVERTER_POWER=my_pv:inverter_power

INFLUX_SENSOR_INVERTER_POWER=SENEC:inverter_power
INFLUX_SENSOR_HOUSE_POWER=SENEC:house_power
INFLUX_SENSOR_GRID_IMPORT_POWER=SENEC:grid_power_plus
INFLUX_SENSOR_GRID_EXPORT_POWER=SENEC:grid_power_minus
INFLUX_SENSOR_BATTERY_CHARGING_POWER=SENEC:bat_power_plus
INFLUX_SENSOR_BATTERY_DISCHARGING_POWER=SENEC:bat_power_minus
INFLUX_SENSOR_BATTERY_SOC=SENEC:bat_fuel_charge
INFLUX_SENSOR_WALLBOX_POWER=SENEC:wallbox_charge_power
INFLUX_SENSOR_WALLBOX_CAR_CONNECTED=SENEC:ev_connected
INFLUX_SENSOR_CASE_TEMP=SENEC:case_temp
INFLUX_SENSOR_SYSTEM_STATUS=SENEC:current_state
INFLUX_SENSOR_SYSTEM_STATUS_OK=SENEC:current_state_ok
INFLUX_SENSOR_GRID_EXPORT_LIMIT=SENEC:power_ratio
INFLUX_SENSOR_INVERTER_POWER_FORECAST=
INFLUX_SENSOR_HEATPUMP_POWER=
INFLUX_SENSOR_CAR_BATTERY_SOC=

# Optional: Exclude sensors from house power calculation
# Default is HEATPUMP_POWER (if defined)
# INFLUX_EXCLUDE_FROM_HOUSE_POWER=HEATPUMP_POWER,WALLBOX_POWER

##################################################################
###                      SENEC Collector                       ###
##################################################################

# The adapter to use
# Values: local, cloud
SENEC_ADAPTER=cloud

# The IP address or hostname of your SENEC device
# Available only when using the local adapter
# SENEC_HOST=192.168.0.0

# The schema protocol to use
# Available only when using the local adapter
# Values: http, https
# SENEC_SCHEMA=https

# The language to use for status strings
# Available only when using the local adapter
# Values: de, en, it
# SENEC_LANGUAGE=de

# The credentials for mein-senec.de
# Available only when using the cloud adapter
SENEC_USERNAME=
SENEC_PASSWORD=

# The system ID of your SENEC device
# Available only when using the cloud adapter
# Can be empty if there is just one system
# SENEC_SYSTEM_ID=123456

# The interval in seconds for polling
# Minimum for local adapter is 5 seconds
# Minimum for cloud adapter is 30 seconds
SENEC_INTERVAL=60

# Measurement name for InfluxDB
INFLUX_MEASUREMENT_SENEC=SENEC

# Optional: Disable specific fields you do not want to send to InfluxDB.
# This can be useful if you are tracking them from another source.
# Comma separated list of fields, no whitespace. Example:
# SENEC_IGNORE=wallbox_charge_power,grid_power_minus

##################################################################
###                       Power Splitter                       ###
##################################################################

# Interval in seconds to run the calculation (default: 3600, min: 300)
# POWER_SPLITTER_INTERVAL=3600

##################################################################
###                 InfluxDB time series database              ###
##################################################################

# InfluxDB host
INFLUX_HOST=influxdb

# InfluxDB schema (http or https)
INFLUX_SCHEMA=http

# InfluxDB port
INFLUX_PORT=8086

# Credentials for the InfluxDB, don't change after the first run!
INFLUX_ORG=solectrus
INFLUX_USERNAME=admin
INFLUX_PASSWORD=ExAmPl3PA55W0rD
INFLUX_ADMIN_TOKEN=my-super-secret-admin-token

# Set these names before first run, they can't be changed later!
INFLUX_BUCKET=solectrus

# To keep things simple, we use ONE token (INFLUX_ADMIN_TOKEN) for both writing and reading.
# For better security, you can use two separate tokens, created via the InfluxDB frontend.
INFLUX_TOKEN_WRITE=my-super-secret-admin-token
INFLUX_TOKEN_READ=my-super-secret-admin-token

# Volume path for storing the InfluxDB data
INFLUX_VOLUME_PATH=./influxdb

##################################################################
###                    PostgreSQL database                     ###
##################################################################

# Volume path for storing the PostgreSQL data
DB_VOLUME_PATH=./postgresql

##################################################################
###                 Redis in-memory database                   ###
##################################################################

# Volume path for storing the database snapshot
REDIS_VOLUME_PATH=./redis

# URL of the Redis database
REDIS_URL=redis://redis:6379/1
```
